add ServiceMapping struct
baetyl/baetyl-go pull request #182
Opened 2020-09-15 06:16 UTC by chensheng0

2020-09-15 08:49 UTC, ludanfeng requested changes

2020-09-15 08:49 UTC, ludanfeng commented on context/context.go
> +	KeyRuntimeDynamicPort  = "BAETYL_SERVICE_DYNAMIC_PORT"
KeyRuntimeDynamicPort --> KeyServiceDynamicPort
动态端口不是function专用的

2020-09-15 08:49 UTC, ludanfeng commented on native/mapping.go
>  	Items  []int `yaml:"items,omitempty"`
没有items这层字段了，inline?
service-1:
  ports: [1,2,3]

2020-09-15 08:49 UTC, ludanfeng commented on native/mapping.go
> +	err = watcher.Add(ServiceMappingFile)
文件不存在会咋样？

2020-09-15 08:49 UTC, ludanfeng commented on native/mapping.go
> +	watcher, err := fsnotify.NewWatcher()
watcher已经不是局部变量了

2020-09-15 08:49 UTC, ludanfeng commented on native/mapping.go
> +func (s *ServiceMapping) AddServicePorts(serviceName string, ports []int) error {
AddServicePorts
DeleteServicePorts
这两个接口你还没想好吧？
怎么处理端口复用？已经分配过端口的实例是不需要再分配新的端口号的

2020-09-15 08:52 UTC, ludanfeng commented on native/mapping.go
>  	Items  []int `yaml:"items,omitempty"`
可能还得指导实例名称吧？否则怎么避免给同一个实例重新分配端口。或者说我们定好只要更新app就重新分配？

2020-09-15 08:56 UTC, chensheng0 commented on native/mapping.go
> +	err = watcher.Add(ServiceMappingFile)
2020/09/15 16:53:54 lstat /tmp/xxx: no such file or directory

2020-09-15 08:56 UTC, chensheng0 commented on native/mapping.go
>  	Items  []int `yaml:"items,omitempty"`
我选择更新app，重新分配端口。也就是现在的实现

2020-09-15 13:53 UTC, ludanfeng requested changes

2020-09-15 13:53 UTC, ludanfeng commented on native/mapping.go
> +	s.watcher = watcher
既然不是局部变量了，在new函数里初始化吧

2020-09-15 13:53 UTC, ludanfeng commented on utils/port.go
> +func CheckPortAvailable(port int) bool {
127.0.0.1 和 0.0.0.0 的port是不一样的，所以上一个函数传了host。进程模式的runtime不应该暴露到宿主机外，所以应该检查127.0.0.1:<port>

2020-09-16 02:55 UTC, chensheng0 commented on utils/port.go
> +func CheckPortAvailable(port int) bool {
done

2020-09-16 02:55 UTC, chensheng0 commented on native/mapping.go
> +	s.watcher = watcher
core 不会调用 watch，function 需要调用，所以不在 New 方法里初始化

2020-09-16 03:26 UTC, ludanfeng requested changes

2020-09-16 03:26 UTC, ludanfeng commented on native/mapping.go
> +				s.error = err
改error没加锁。把要保护的对象梳理一下吧。

2020-09-16 03:33 UTC, ludanfeng approved these changes

2020-09-16 03:33 UTC, ludanfeng commented on native/mapping.go
> +				err := s.load()
这个err也得赋值给s.error

2020-09-16 03:42 UTC, merged